defaults:
  - /encoder@encoders.optical: vit_small
  - /encoder@encoders.sar: vit_small
  - _self_

_target_: getsits.encoders.comm.CoMMEncoder
model_name: "CoMM"
input_size: 224
input_bands:
  optical: ${encoder.encoders.optical.input_bands.optical}
  sar: ${encoder.encoders.sar.input_bands.sar}
embed_dim: 256
output_layers: [1, 2, 3, 4]
output_dim: [768, 768, 768, 512] 
multi_temporal: False
multi_temporal_output: False
pyramid_output: False
encoder_weights: ""
download_url: ""
num_heads: 8
depth: 1
modalities_finetune:
  optical: True
  sar: True
modalities_from_scratch:
  optical: False
  sar: False

encoders:
  sar:
    input_bands:
      sar: ['VV', 'VH']