_target_: getsits.encoders.comm_vit.MMFusion
model_name: comm_vit
encoder_weights: null

embed_dim: 512
depth: 12
num_heads: 8
fusion: "concat"    # Opciones: "concat" o "x-attn"
pool: "cls"         # Opciones: "cls" o "mean"
dropout: 0.5        # Dropout para el AlexNetEncoder

input_size: 227
multi_temporal: True
multi_temporal_output: False
pyramid_output: False
projection_dim: 256
positional_encoding: "geotime"

modalities_finetune:
  optical: True
  sar: True
input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B11
    - B12
  sar: ${dataset.bands.sar}

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 512